# Generated by Django 3.1 on 2020-08-18 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=250)),
                ('emailId', models.EmailField(max_length=250, unique=True)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('password', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogDateTime', models.DateTimeField(auto_created=True, auto_now=True)),
                ('title', models.CharField(max_length=350)),
                ('excerpt', models.CharField(max_length=1000)),
                ('blog', models.CharField(max_length=10000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApplication.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentDateTime', models.DateTimeField(auto_created=True, auto_now=True)),
                ('readerName', models.CharField(max_length=250)),
                ('readerEmail', models.EmailField(max_length=250)),
                ('readerComment', models.CharField(max_length=5000)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApplication.blog')),
            ],
        ),
    ]
